/* eslint-disable react/no-children-prop */
/* eslint-disable @next/next/no-img-element */
import React from 'react'
import Head from 'next/head'
import { useUser } from '@/store/contexts/UserContect'
import Ico from '@/components/icon'
import Modal from '@/components/useModal/Modal'
import PostModal from '@/components/Modals/PostModal'
import AskModal from '@/components/Modals/AskModal'

export default function Home() {
  const { user } = useUser()

  const [askQuestionModalOpen, setAskQuestionModalOpen] =
    React.useState<boolean>(false)
  const [postContentModalOpen, setPostContentModalOpen] =
    React.useState<boolean>(false)

  const openAskQuestionModal = () => {
    setAskQuestionModalOpen(true)
  }
  const closeAskQuestionModal = () => {
    setAskQuestionModalOpen(false)
  }
  const openPostContentModal = () => {
    setPostContentModalOpen(true)
  }
  const closePostContentModal = () => {
    setPostContentModalOpen(false)
  }

  return (
    <>
      <Head>
        <title>Javobho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full h-full flex justify-center items-center sm:px-[20px] flex-col">
          <div className="border border-invisible border-t-0 p-[10px_15px] flex-col gap-[15px] flex sm:w-[420px] w-full">
            <div className="flex gap-[10px]">
              <img
                src={user.avatar}
                alt="profile"
                className="sm:w-[40px] sm:h-[40px] w-[30px] h-[30px] rounded-full object-cover"
              />
              <input
                placeholder="What do you want to ask or share?"
                className="border outline-none p-[5px] rounded-lg border-invisible sm:w-[350px] w-full"
              />
            </div>
            <div className="flex justify-between w-full">
              <button
                onClick={openAskQuestionModal}
                className="p-[5px_15px]  flex sm:gap-[15px] gap-[5px] items-center justify-between rounded-[10px] text-lighterIndigo hover:bg-main hover:text-white transition-colors duration-500"
              >
                <Ico name="ask" />
                Ask
              </button>
              <button className="p-[5px_15px]  flex sm:gap-[15px] gap-[5px] items-center justify-between rounded-[10px] text-lighterIndigo hover:bg-main hover:text-white transition-colors duration-500">
                <Ico name="answer" />
                Answer
              </button>
              <button
                onClick={openPostContentModal}
                className="p-[5px_15px]  flex sm:gap-[15px] gap-[5px] items-center justify-between rounded-[10px] text-lighterIndigo hover:bg-main hover:text-white transition-colors duration-500"
              >
                <Ico name="post" />
                Post
              </button>
            </div>
          </div>

          {/* Modals */}
          <Modal
            isOpen={askQuestionModalOpen}
            closeModal={closeAskQuestionModal}
            children={<AskModal />}
            title="Ask Question"
          />
          <Modal
            isOpen={postContentModalOpen}
            closeModal={closePostContentModal}
            children={<PostModal />}
            title="Post Content"
          />
        </div>
      </main>
    </>
  )
}
