name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
        run:
            working-directory: "/var/www/fastuser/data/www/"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Rename source
        run: mv /var/www/fastuser/data/actions-runner/_work/JavobhoVersion/JavobhoVersion  /var/www/fastuser/data/actions-runner/_work/JavobhoVersion/javobho.com  
      - name: Copy source
        run: cp -R /var/www/fastuser/data/actions-runner/_work/JavobhoVersion/javobho.com/  ./

      - name: Build and Archive
        run: |
          npm ci
          npm run build

      
