name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print server data
        run: |
          echo "Server Host: ${{ secrets.SERVER_HOST }}"
          echo "Server Username: ${{ secrets.SERVER_USERNAME }}"
          echo "Server Private Key: ${{ secrets.SERVER_PRIVATE_KEY }}"

      - name: Build and Archive
        run: |
          npm ci
          npm run build
          tar -cjf build.tar.bz2 ./build/

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: ./build.tar.bz2
          target: /var/www/fastuser/data/www/javobho.com
